### ISSUE TITLE
NS SAREGISTER fails, disconnects the client

### ISSUE THREAD

**Issue by slingamn** [ergochat/ergo#1898]
Reported by @FiskFan1999 : https://gist.github.com/FiskFan1999/948eecbd1a69ed3b015bdf359e4ac606

This is a regression introduced in 9ff4047fa650bc9873e58b7d8d6faf58df72922d.

**Comment by slingamn** [comment]
Copying the stack trace in here for completeness:

```
goroutine 105 [running]:
runtime/debug.Stack()
	/home/ergo/go/src/runtime/debug/stack.go:24 +0x65
github.com/ergochat/ergo/irc.(*Client).run.func1()
	/home/ergo/ergo/irc/client.go:614 +0x5d
panic({0x896fe0, 0xcbb610})
	/home/ergo/go/src/runtime/panic.go:1038 +0x215
github.com/ergochat/ergo/irc.(*Client).Nick(0x0)
	/home/ergo/ergo/irc/getters.go:160 +0x34
github.com/ergochat/ergo/irc.(*AccountManager).Register(0xc00020c400, 0x0, {0xc00050c37d, 0x6}, {0x905ac7, 0xc0005511e8}, {0x0, 0x0}, {0xc00050c384, 0x5}, ...)
	/home/ergo/ergo/irc/accounts.go:478 +0xb88
github.com/ergochat/ergo/irc.(*AccountManager).SARegister(0x0, {0xc00050c37d, 0x6}, {0xc00050c384, 0xc000551340})
	/home/ergo/ergo/irc/accounts.go:953 +0x65
github.com/ergochat/ergo/irc.nsSaregisterHandler(0x91333a, 0xc00020c400, 0x907f1f, {0x8, 0xc000551340}, {0xc0004a8ca0, 0x1, 0x87}, 0x87)
	/home/ergo/ergo/irc/nickserv.go:1022 +0x9a
github.com/ergochat/ergo/irc.serviceRunCommand(0xcc3f00, 0xc00020c400, 0xa, 0xc0000bd560, {0xc00050c372, 0x26}, {0xc0004a8ca0, 0x2, 0x2}, 0xc000203280)
	/home/ergo/ergo/irc/services.go:226 +0x60a
github.com/ergochat/ergo/irc.servicePrivmsgHandler(0xcc3f00, 0x8, 0xc00050c372, {0xc00050c372, 0x17}, 0x1a)
	/home/ergo/ergo/irc/services.go:164 +0x26a
github.com/ergochat/ergo/irc.dispatchMessageToTarget(0xc000204e00, 0x0, 0x1, {0xc00050c360, 0xc000020ca0}, {0xc00050c368, 0x9c3770}, {{0xc00050c372, 0x17}, {0xc0001b0740, ...}, ...}, ...)
	/home/ergo/ergo/irc/handlers.go:2249 +0xdb4
github.com/ergochat/ergo/irc.messageHandler(0xc00020c400, 0xc000551c38, {{0x0, 0x0}, {0xc00050c360, 0x7}, {0xc000020ca0, 0x2, 0x2}, 0x0, ...}, ...)
	/home/ergo/ergo/irc/handlers.go:2194 +0x74e
github.com/ergochat/ergo/irc.(*Command).Run.func1(0xc000203280, 0xc000204e00, 0x7, 0xc00020c400, {{0x0, 0x0}, {0xc00050c360, 0x7}, {0xc000020ca0, 0x2, ...}, ...}, ...)
	/home/ergo/ergo/irc/commands.go:47 +0x2a7
github.com/ergochat/ergo/irc.(*Command).Run(0xc00050c360, 0x0, 0xc000204e00, 0xc0000a42c0, {{0x0, 0x0}, {0xc00050c360, 0x7}, {0xc000020ca0, 0x2, ...}, ...})
	/home/ergo/ergo/irc/commands.go:48 +0x178
github.com/ergochat/ergo/irc.(*Client).run(0xc000204e00, 0xc0000a42c0)
	/home/ergo/ergo/irc/client.go:706 +0x6f1
created by github.com/ergochat/ergo/irc.(*Client).run
	/home/ergo/ergo/irc/client.go:711 +0xa6f
```
