### ISSUE TITLE
mysql is broken on 32-bit architectures

### ISSUE THREAD

**Issue by slingamn** [ergochat/ergo#1969]
Reported by hauser in the support channel:

```
2022-06-10T12:11:54.847Z : info  : server     : ergo-2.10.0 starting
2022-06-10T12:11:54.847Z : info  : server     : Using config file : ircd.yaml
2022-06-10T12:11:54.848Z : info  : server     : Using datastore : ircd.db
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x1dc6f54, 0xb2d05e00)
	runtime/internal/atomic/atomic_arm.s:291 +0x14
github.com/ergochat/ergo/irc/mysql.(*MySQL).SetConfig(0x1dc6f54, {0x1, {0x1d9b5a0, 0x9}, 0xcea, {0x0, 0x0}, {0x1d9b5c0, 0x4}, {0x1d9b5d0, ...}, ...})
	github.com/ergochat/ergo/irc/mysql/history.go:72 +0x30
github.com/ergochat/ergo/irc/mysql.(*MySQL).Initialize(...)
	github.com/ergochat/ergo/irc/mysql/history.go:68
github.com/ergochat/ergo/irc.(*Server).loadFromDatastore(0x1dc6dc0, 0x1cc5500)
	github.com/ergochat/ergo/irc/server.go:845 +0x1d0
github.com/ergochat/ergo/irc.(*Server).applyConfig(0x1dc6dc0, 0x1cc5500)
	github.com/ergochat/ergo/irc/server.go:714 +0xc24
github.com/ergochat/ergo/irc.NewServer(0x1cc5500, 0x1f97500)
	github.com/ergochat/ergo/irc/server.go:115 +0x3b8
main.main()
	./ergo.go:194 +0xe7c
```

**Comment by slingamn** [comment]
This was `ergo-2.10.0-linux-armv6.tar.gz` running on a Raspberry Pi Zero 2 W with the armv7l kernel.
